---
# tasks file for dotfiles
- block:
  - name: clone dotfiles
    git:
      repo: git@github.com:sfus/dotfiles.git
      dest: '{{ dotfiles_dir }}'
      accept_hostkey: true

  # - name: install oh-my-zsh
  #   shell: "curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh"
  #   args:
  #     creates: ~/.oh-my-zsh

  - name: clone tmux-powerline
    git:
      repo: https://github.com/erikw/tmux-powerline.git
      dest: ~/.tmux-powerline

  - name: init vim
    command: "{{ dotfiles_dir }}/vim/init_vim.sh"
    changed_when: false

  - name: create symbolic links to dotfiles
    command: "{{ dotfiles_dir }}/create_symlink.sh"
    changed_when: false

  tags:
    - dotfiles
