---
# vars file for java
sdkman_dir: ~/.sdkman
sdkman_packages:
  - { command: java, id: 8.0.322-tem }
  - { command: java, id: 11.0.14-tem }
  - { command: java, id: 17.0.1-tem }
sdkman_defaults:
  - { command: java, id: 11.0.14-tem }
