---
# tasks file for nodejs using Volta
- block:

  - block:
    - name: check volta
      ansible.builtin.stat:
        path: "{{ nodejs_volta_dir }}"
      register: volta_dir_stat

    - name: install volta
      ansible.builtin.shell: "curl https://get.volta.sh | bash"
      when: volta_dir_stat.stat.isdir is not defined and not ansible_check_mode

    - name: install and set default node
      ansible.builtin.command: "{{ nodejs_volta_dir }}/bin/volta install node@{{ nodejs_node_version }}"
      register: volta_node_install
      changed_when: "'was set as default' in volta_node_install.stderr or 'installed and set' in volta_node_install.stderr"

    tags: volta

  - block:
    - name: install global node packages via volta
      ansible.builtin.command: "{{ nodejs_volta_dir }}/bin/volta install {{ item.name }}"
      with_items: '{{ nodejs_global_packages | default([]) }}'
      register: volta_global_install
      changed_when: "'installed' in volta_global_install.stderr"

    tags: node-global

  tags: nodejs
