---
# tasks file for nodejs
# https://github.com/riywo/ndenv
- block:

  - block:
    - name: check ndenv dir
      stat:
        path: "{{ nodejs_ndenv_dir }}"
      register: dir_stat

    - name: install ndenv
      git:
        repo: https://github.com/riywo/ndenv
        dest: "{{ nodejs_ndenv_dir }}"
      when: dir_stat.stat.isdir is not defined and not ansible_check_mode

    - name: install node-build
      git:
        repo: https://github.com/riywo/node-build.git
        dest: "{{ nodejs_ndenv_dir }}/plugins/node-build"
      when: dir_stat.stat.isdir is not defined and not ansible_check_mode

    - name: install node
      command: "{{ nodejs_ndenv_dir }}/bin/ndenv install {{ nodejs_node_version }}"
      register: nodejs_ndenv_node_result
      changed_when: "'Installed node' in nodejs_ndenv_node_result.stderr"
      failed_when: "nodejs_ndenv_node_result.rc != 0 and 'already exists' not in nodejs_ndenv_node_result.stderr"

    - name: set global
      command: "{{ nodejs_ndenv_dir }}/bin/ndenv global {{ nodejs_node_version }}"
      changed_when: false

    tags: ndenv

  - block:
    - name: install npm -g
      npm:
        name: "{{ item.name }}"
        executable: "{{ nodejs_ndenv_dir }}/shims/npm"
        global: yes
      with_items: '{{ nodejs_npm_packages | default([]) }}'

    tags: npm

  tags: nodejs
