---
# tasks file for nodejs using nvm
- block:

  - block:
    - name: check nvm dir
      stat:
        path: "{{ nodejs_nvm_dir }}"
      register: dir_stat

    - name: install nvm
      git:
        repo: https://github.com/nvm-sh/nvm.git
        dest: "{{ nodejs_nvm_dir }}"
      when: dir_stat.stat.isdir is not defined and not ansible_check_mode

    - name: source nvm script
      shell: . "{{ nodejs_nvm_dir }}/nvm.sh"
      args:
        executable: /bin/bash

    - name: install node versions
      shell: ". {{ nodejs_nvm_dir }}/nvm.sh && nvm install {{ item }}"
      with_items: '{{ nodejs_node_versions }}'
      register: node_install_results

    - name: set default node version
      shell: ". {{ nodejs_nvm_dir }}/nvm.sh && nvm alias default {{ nodejs_node_default_version }}"

    - name: install npm globally
      shell: ". {{ nodejs_nvm_dir }}/nvm.sh && npm install -g npm@{{ nodejs_npm_default_version }}"

    tags: nvm

  - block:
    - name: install global npm packages
      shell: ". {{ nodejs_nvm_dir }}/nvm.sh && npm install -g {{ item.name }}"
      with_items: '{{ nodejs_npm_packages | default([]) }}'

    tags: npm

  tags: nodejs
