---
# tasks file for python
- block:
  - name: install python via homebrew
    community.general.homebrew:
      name: "python@{{ python_version }}"
      state: present

  - name: symlink python3 to python
    ansible.builtin.file:
      src: '{{ python_homebrew_root }}/bin/python3'
      dest: '{{ python_homebrew_root }}/bin/python'
      state: link
  tags: python
