---
# vars file for python
# $ pyenv install --list
python_pyenv_dir: ~/.pyenv
python_python3_version: 3.7.2
python_python2_version: 2.7.15
pip_packages:
  - name: Pygments
  - name: jedi
  - name: epc
  - name: scipy
  - name: gensim
  - name: mecab-python3
  - name: online-judge-tools
