---
# tasks file for homebrew
- block:
  - block:
    - name: update homebrew
      homebrew:
        update_homebrew: yes

    - name: tap homebrew
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps | default([]) }}'
    tags: homebrew-update-and-tap

  - block:
    - name: install homebrew my packages
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_my_packages | default([]) }}'
    tags: homebrew-install-mine

  - block:
    - name: install homebrew packages
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
        install_options: '{{ item.install_options | default([]) }}'
      with_items: '{{ homebrew_packages | default([]) }}'
    tags: homebrew-install

  - block:
    - name: install homebrew other packages
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_other_packages | default([]) }}'
    tags: homebrew-install-others

  - block:
    - name: symlink ggrep (GNU grep) to grep
      file:
        src: '{{ homebrew_root }}/bin/ggrep'
        dest: '{{ homebrew_root }}/bin/grep'
        state: link
    tags: homebrew-symlink-grep

  - block:
    - name: symlink gtime (GNU time) to time
      file:
        src: '{{ homebrew_root }}/bin/gtime'
        dest: '{{ homebrew_root }}/bin/time'
        state: link
    tags: homebrew-symlink-gtime

  - block:
    - name: check gcc version
      shell: "brew info gcc | head -1 | awk '{print $3}' | cut -d. -f1"
      register: homebrew_check_gcc_version
      changed_when: false

    - name: create symlink GNU g++
      file:
        src: '{{ homebrew_root }}/bin/g++-{{ homebrew_check_gcc_version.stdout }}'
        dest: '{{ homebrew_root }}/bin/g++'
        state: link

    tags: homebrew-symlink-g++

  - block:
    - name: create directory for bits/stdc++.h
      file:
        path: '{{ homebrew_root }}/include/bits'
        state: directory
        mode: '0755'

    - name: check stdc++.h location
      shell: "find {{ homebrew_root }}/Cellar/gcc -name 'stdc++.h' | grep {{ homebrew_check_gcc_version.stdout }}"
      register: homebrew_check_stdcpp_h_location
      changed_when: false

    - name: copy bits/stdc++.h
      copy:
        src: '{{ homebrew_check_stdcpp_h_location.stdout }}'
        dest: '{{ homebrew_root }}/include/bits/stdc++.h'
        mode: '0644'

    tags: homebrew-copy-bits

  # - block:
  #   - name: check gtags (GNU global) for pygments
  #     shell: gtags --debug 2> /dev/null
  #     register: homebrew_check_gtags
  #     failed_when: homebrew_check_gtags.rc != 0
  #     changed_when: false
  #   tags: homebrew-check-gtags

  - block:
    - name: update brew list
      shell: brew list > brewlist.txt
      changed_when: false
    tags: homebrew-diff

  tags:
    - homebrew
