---
# tasks file for fonts

- block:

  - name: Download migu1m
    get_url:
      url: https://github.com/itouhiro/mixfont-mplus-ipa/releases/download/v2020.0307/migu-1m-20200307.zip
      dest: ~/Downloads/migu-1m-20200307.zip
      force: true

  - name: Unzip migu1m
    ansible.builtin.unarchive:
      src: "~/Downloads/migu-1m-20200307.zip"
      dest: "~/Downloads"
    changed_when: false

  - name: clone fontpatcher
    git:
      repo: https://github.com/powerline/fontpatcher.git
      dest: ~/Downloads/fontpatcher

  - name: patch font
    command: "fontforge powerline-fontpatcher {{ item }}"
    args:
      chdir: ~/Downloads/fontpatcher/scripts
    changed_when: false
    with_fileglob:
      - ~/Downloads/migu-1m-20200307/*.ttf

  - name: copy *.ttf to  ~/Library/Fonts/
    copy:
      src: "{{ item }}"
      dest: "~/Library/Fonts"
    changed_when: false
    with_fileglob:
      - ~/Downloads/fontpatcher/scripts/*.ttf

  - name: fc-cache
    command: fc-cache -vf
    changed_when: false

  tags:
    - fonts
